version: '3'


services:
  django: &django
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    image: hephaestus:latest
    container_name: hephaestus_service
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    ports:
      - "8000:8000"
    volumes:
      - ./logs/:/app/logs
      - ./keys/:/app/keys
      - ./fixtures/:/app/fixtures
      - ./media/:/app/media
      - ./staticfiles/:/app/staticfiles
    links:
      - db
    command: /start-server

  db:
    image: postgres:14
    container_name: hephaestus_db
    environment:
      - POSTGRES_HOST_AUTH_METHOD=md5
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=hephaestus
      - PGUSER=postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
